language: php

php:
  - 7.0
  - 7.1

sudo: false

before_install:
  - composer self-update
  - composer config -g github-oauth.github.com "$GITHUB_TOKEN"

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

env:
  global:
    - secure: ilZ2lZFtaC2/mx+yqLs/unKKJ0HnZQG+UI/hDIeyZmekqC2+KlUur+rCC1/yMA3rshWLkctWg9L5Uitqg9UCPf6UZ199i38uv4fp4yRlRo2IPp48CBhHWIP8K6tahISy+gqoc+QuOeJte8DoleRxLgz7qA73ne28a556ZDxUJW+LiBiwjeTMJOZWDxI0zVaiohn0RD+JBv8ivOFZzzSQFFtidpD9ZXlj5nFhN6BHjKiSzPO2ByNOFzK7vxvn2LIpWI3V/I9n3dxhtlhHY+XSCS52QWi+kYZ44964CyeURwACnO/O8/g5+Ky3qzavxEgxCdhUpyJoWH1eAcZgEJ6QgvJQq4F4a3Mn2HvXmhah9sJ3TWPBzjSWnDlmtrh2lSep0HjJzYkg370rFLSy+qw2pqHpRLGevnwR2Agz4PGe552r/iNy8xDbRHQq0iQf5Q/CnFmfJprNEfjaNkCpL7JjVdfvg078KStrlT9wd42uL/uMYr4ukrP6e1sN/f9FUULnZKzFTm2Diiw0COkT7iwPgZcoZlcy1vGrVnIWPlotLaVsUhPnCRUjASCtE7jCQLeEcT7wKXaIuiVTuCR8eO/+mz0zxkdOzAM1fGffxk+9Z61Wpy6vycpZnEg2Y1vBDPlL219MIFs+DJ60mDag2iPkDqD/ZYLFb+QBJ/t0ozonROQ=
